name: ASP.NET
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
    schedule:
      - cron: "0 8 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_CONN_STR: ${{ vars.DB_CONN_STR }}
      DB_USERNAME: ${{ vars.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - name: Check Memory Free
        run: |
          free -m
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore Couchbase.TravelSample.sln
      - name: Build
        run: dotnet build Couchbase.TravelSample.sln --configuration Debug --no-restore
      - name: Test
        run: timeout 300 dotnet test Couchbase.TravelSample.sln --configuration Debug --no-build --verbosity normal
      - name: Report Status
        if: always()
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          notify_when: "failure,warnings"
          notification_title: "Repo: *{repo}*"
          message_format: "{emoji}    *{status_message}* in <{repo_url}|{repo}@{branch}> on <{commit_url}|{commit_sha}>"
          footer: "<{run_url}|View Full Run on GitHub>"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}